### GET all
GET http://localhost:3000/announcements

### GET search
GET http://localhost:3000/announcements?search=asus

### GET sort + page
GET http://localhost:3000/announcements?sort=oldest&page=2

### GET by id
GET http://localhost:3000/announcements/1

### GET not found
GET http://localhost:3000/announcements/9999

### POST valid
POST http://localhost:3000/announcements
Content-Type: application/json

{
  "title": "Продам ноутбук ASUS",
  "description": "Чудовий стан, майже новий",
  "price": 18000,
  "category": "sale",
  "contactInfo": "0991234567"
}

### POST invalid
POST http://localhost:3000/announcements
Content-Type: application/json

{
  "title": "abc"
}

### PATCH
PATCH http://localhost:3000/announcements/1
Content-Type: application/json

{
  "price": 15000
}

### DELETE
DELETE http://localhost:3000/announcements/1


### REGISTER
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "ivan",
  "password": "123456",
  "name": "Ivan"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "ivan",
  "password": "123456"
}

### ME (after login - встав token)
GET http://localhost:3000/auth/me
Authorization: Bearer YOUR_TOKEN_HERE

### REFRESH
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "YOUR_REFRESH_TOKEN"
}

### LOGOUT
POST http://localhost:3000/auth/logout
Authorization: Bearer YOUR_TOKEN_HERE

### PATCH invalid token
PATCH http://localhost:3000/announcements/999
Authorization: Bearer fake_token

### ME without token
GET http://localhost:3000/auth/me

### PATCH чужого оголошення
PATCH http://localhost:3000/announcements/2
Authorization: Bearer YOUR_TOKEN_HERE
Content-Type: application/json

{
  "price": 100
}

### DELETE forbidden
DELETE http://localhost:3000/announcements/2
Authorization: Bearer YOUR_TOKEN_HERE